import Foundation

enum WorkoutGeneratorService {

    static func autoGeneratedRoutineName(goal: PrimaryGoal) -> String {
        String(
            localized: "routine_generator.auto_name",
            defaultValue: "Rutina personalizada - \(goal.displayName)",
            bundle: AppLanguage.current.bundle,
            locale: AppLanguage.current.locale
        )
    }

    static func manualRoutineName(split: SplitType) -> String {
        String(
            localized: "routine_generator.manual_name",
            defaultValue: "Rutina manual - \(split.displayName)",
            bundle: AppLanguage.current.bundle,
            locale: AppLanguage.current.locale
        )
    }

    struct DayTemplate {
        let slot: DaySlot
        var title: String { slot.displayName }
        var muscleGroups: [MuscleGroup] { slot.muscleGroups }
    }

    static func splitType(for daysPerWeek: Int) -> SplitType {
        switch daysPerWeek {
        case ...2: return .fullBody
        case 3...4: return .upperLower
        default: return .pushPullLegs
        }
    }

    static func dayTemplates(split: SplitType, dayCount: Int) -> [DayTemplate] {
        let cycle: [DayTemplate]
        switch split {
        case .fullBody:
            cycle = [DayTemplate(slot: .fullBody)]
        case .upperLower:
            cycle = [DayTemplate(slot: .upper), DayTemplate(slot: .lower)]
        case .pushPullLegs:
            cycle = [DayTemplate(slot: .push), DayTemplate(slot: .pull), DayTemplate(slot: .legs)]
        }

        return (0..<max(1, dayCount)).map { cycle[$0 % cycle.count] }
    }

    static func weekdaysForCount(_ count: Int) -> [Weekday] {
        switch count {
        case 1: return [.monday]
        case 2: return [.monday, .thursday]
        case 3: return [.monday, .wednesday, .friday]
        case 4: return [.monday, .tuesday, .thursday, .friday]
        case 5: return [.monday, .tuesday, .wednesday, .thursday, .friday]
        case 6: return [.monday, .tuesday, .wednesday, .thursday, .friday, .saturday]
        default: return Weekday.allCases // 7 dias: los 7 casos del enum, ya en orden
        }
    }

    /// Misma tabla que `weekdaysForCount(_:)`, rotada para que el primer
    /// dia caiga en `start` en vez de siempre lunes — preserva el mismo
    /// patron de espaciado entre sesiones, solo cambia el punto de partida.
    static func weekdaysForCount(_ count: Int, startingFrom start: Weekday) -> [Weekday] {
        let mondayAnchored = weekdaysForCount(count)
        return mondayAnchored.map { weekday in
            let offsetFromMonday = weekday.rawValue - Weekday.monday.rawValue
            let newRaw = (start.rawValue - 1 + offsetFromMonday) % 7 + 1
            return Weekday(rawValue: newRaw) ?? start
        }
    }

    struct Prescription {
        let sets: Int
        let repsMin: Int
        let repsMax: Int
        let restSeconds: Int
    }

    static func prescription(goal: PrimaryGoal, level: ExperienceLevel) -> Prescription {
        switch goal {
        case .strength:
            return Prescription(sets: level == .advanced ? 5 : 4, repsMin: 3, repsMax: 6, restSeconds: 150)
        case .hypertrophy:
            return Prescription(sets: level == .beginner ? 3 : 4, repsMin: 8, repsMax: 12, restSeconds: 75)
        case .fatLoss:
            return Prescription(sets: 3, repsMin: 12, repsMax: 15, restSeconds: 40)
        }
    }

    static func exercisesPerDay(for level: ExperienceLevel) -> Int {
        switch level {
        case .beginner: return 4
        case .intermediate: return 5
        case .advanced: return 6
        }
    }

    static func generateRoutine(for profile: UserProfile, catalog: [Exercise], today: Weekday = Weekday.today()) -> WorkoutRoutine {
        let split = splitType(for: profile.workoutDaysPerWeek)
        let templates = dayTemplates(split: split, dayCount: profile.workoutDaysPerWeek)
        let plan = prescription(goal: profile.primaryGoal, level: profile.experienceLevel)
        let perDay = exercisesPerDay(for: profile.experienceLevel)
        let weekdays = weekdaysForCount(templates.count, startingFrom: today)

        let routine = WorkoutRoutine(
            name: autoGeneratedRoutineName(goal: profile.primaryGoal),
            splitType: split,
            isAutoGenerated: true,
            isActive: true
        )

        for (index, template) in templates.enumerated() {
            let picked = selectExercises(for: template, from: catalog, limit: perDay)
            let day = RoutineDay(dayNumber: index + 1, title: template.title, weekday: weekdays[index])

            // Solo se asigna el lado "coleccion" de cada relacion: SwiftData completa
            // el inverso (RoutineExercise.day, RoutineDay.routine) al insertar.
            // Setear ambos lados a mano puede duplicar entradas.
            day.exercises = picked.enumerated().map { position, exercise in
                RoutineExercise(
                    exercise: exercise,
                    targetSets: plan.sets,
                    targetRepsMin: plan.repsMin,
                    targetRepsMax: plan.repsMax,
                    restSeconds: plan.restSeconds,
                    orderIndex: position
                )
            }

            routine.days.append(day)
        }

        return routine
    }

    /// Compuestos primero, aislamiento despues, y todo el core al final del dia
    /// sin importar si el movimiento es compuesto.
    private static func selectExercises(
        for template: DayTemplate,
        from catalog: [Exercise],
        limit: Int
    ) -> [Exercise] {
        // Round-robin por grupo muscular: sin esto, un grupo sin ejercicios
        // compuestos (ej. biceps, core) nunca entra al dia porque el cupo
        // se llena antes con compuestos de otros grupos.
        let pools = template.muscleGroups.map { group in
            catalog.filter { $0.muscleGroup == group }.shuffled()
        }

        var picked: [Exercise] = []
        var round = 0
        while picked.count < limit && pools.contains(where: { $0.count > round }) {
            for pool in pools where pool.count > round && picked.count < limit {
                picked.append(pool[round])
            }
            round += 1
        }

        let compounds = picked.filter { $0.isCompound && $0.muscleGroup != .core }
        let isolation = picked.filter { !$0.isCompound && $0.muscleGroup != .core }
        let core = picked.filter { $0.muscleGroup == .core }
        return compounds + isolation + core
    }
}
