import Foundation
import SwiftData

@Model
final class WorkoutRoutine {
    @Attribute(.unique) var id: UUID
    var name: String
    var splitType: SplitType
    var isAutoGenerated: Bool
    var isActive: Bool
    var profile: UserProfile?

    @Relationship(deleteRule: .cascade, inverse: \RoutineDay.routine)
    var days: [RoutineDay]

    init(
        id: UUID = UUID(),
        name: String,
        splitType: SplitType,
        isAutoGenerated: Bool = false,
        isActive: Bool = true,
        profile: UserProfile? = nil,
        days: [RoutineDay] = []
    ) {
        self.id = id
        self.name = name
        self.splitType = splitType
        self.isAutoGenerated = isAutoGenerated
        self.isActive = isActive
        self.profile = profile
        self.days = days
    }
}

@Model
final class RoutineDay {
    @Attribute(.unique) var id: UUID
    var dayNumber: Int
    var title: String
    var weekday: Weekday
    var routine: WorkoutRoutine?

    @Relationship(deleteRule: .cascade, inverse: \RoutineExercise.day)
    var exercises: [RoutineExercise]

    init(
        id: UUID = UUID(),
        dayNumber: Int,
        title: String,
        weekday: Weekday = .monday,
        routine: WorkoutRoutine? = nil,
        exercises: [RoutineExercise] = []
    ) {
        self.id = id
        self.dayNumber = dayNumber
        self.title = title
        self.weekday = weekday
        self.routine = routine
        self.exercises = exercises
    }
}

@Model
final class RoutineExercise {
    @Attribute(.unique) var id: UUID
    var exercise: Exercise
    var targetSets: Int
    var targetRepsMin: Int
    var targetRepsMax: Int
    var restSeconds: Int
    var orderIndex: Int
    var day: RoutineDay?

    init(
        id: UUID = UUID(),
        exercise: Exercise,
        targetSets: Int,
        targetRepsMin: Int,
        targetRepsMax: Int,
        restSeconds: Int,
        orderIndex: Int,
        day: RoutineDay? = nil
    ) {
        self.id = id
        self.exercise = exercise
        self.targetSets = targetSets
        self.targetRepsMin = targetRepsMin
        self.targetRepsMax = targetRepsMax
        self.restSeconds = restSeconds
        self.orderIndex = orderIndex
        self.day = day
    }
}

@Model
final class WorkoutLog {
    @Attribute(.unique) var id: UUID
    var startDate: Date
    var endDate: Date?
    var routineName: String
    var dayTitle: String
    var profile: UserProfile?

    @Relationship(deleteRule: .cascade, inverse: \SetLog.session)
    var completedSets: [SetLog]

    init(
        id: UUID = UUID(),
        startDate: Date = Date(),
        endDate: Date? = nil,
        routineName: String,
        dayTitle: String,
        profile: UserProfile? = nil,
        completedSets: [SetLog] = []
    ) {
        self.id = id
        self.startDate = startDate
        self.endDate = endDate
        self.routineName = routineName
        self.dayTitle = dayTitle
        self.profile = profile
        self.completedSets = completedSets
    }
}

@Model
final class SetLog {
    @Attribute(.unique) var id: UUID
    var exerciseId: String
    var setIndex: Int
    var weightKg: Double
    var repsCompleted: Int
    var restSeconds: Int
    var targetRepsMin: Int
    var targetRepsMax: Int
    var isCompleted: Bool
    var timestamp: Date
    var session: WorkoutLog?

    init(
        id: UUID = UUID(),
        exerciseId: String,
        setIndex: Int,
        weightKg: Double,
        repsCompleted: Int,
        restSeconds: Int,
        targetRepsMin: Int,
        targetRepsMax: Int,
        isCompleted: Bool = false,
        timestamp: Date = Date(),
        session: WorkoutLog? = nil
    ) {
        self.id = id
        self.exerciseId = exerciseId
        self.setIndex = setIndex
        self.weightKg = weightKg
        self.repsCompleted = repsCompleted
        self.restSeconds = restSeconds
        self.targetRepsMin = targetRepsMin
        self.targetRepsMax = targetRepsMax
        self.isCompleted = isCompleted
        self.timestamp = timestamp
        self.session = session
    }
}
